server:
  port: 8089
#  ssl:
#    key-store: classpath:www.peteralbus.com.pfx
#    key-alias: alias
#    key-store-password: rl5x8mbi
#    key-store-type: PKCS12

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: remote
    password: shou1951123
    url: jdbc:mysql://peteralbus.com:3306/blogs?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: peteralbus.com
      port: 7000
      password: 0211@redis
      database: 0
  mail:
    host: smtp.163.com
    port:
    username: wuhongdb@163.com
    password: YUPXUUBYGATWMVMX
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.peteralbus.domain
  configuration:
    map-underscore-to-camel-case: true
    # ??????????????? MyBatis ???????????????
    #    call-setters-on-nulls: true
    # ?????????sql?????????????????
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  # token名称 (同时也是cookie名称)
    token-name: satoken_peteralbus_blog
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1



